import { P, S, U, M, PLANT } from './core.mjs';
const X = (id, name, sub, w, v, o) => P(id, name, sub, w, v, { file: 4, ...o });
const u = (arr) => arr.map((s) => { const i = s.indexOf(':'); return i < 0 ? U(s) : U(s.slice(0, i), s.slice(i + 1)); });
// ほかの担当が材料に使っている、まとめ役の品（並品）と足りなかった物
X('planks', '板材', 'wood', 3, 0.6, { d: 3, make: M({ wood: 1 }, 'carpenter', 1, 4), use: u(['build:床・壁・棚', 'craft:箱・机・小物・道具の部品']), desc: 'いろいろな木を混ぜて挽いたふつうの板。大工がいちばん多く使う。' });
X('yarn', '紡ぎ糸', 'yarn', 0.2, 1.2, { d: 2, make: M({ hemp_fiber: 1 }, 'weaver', 6), use: u(['craft:機織り・縫い物・刺繍・お守りの紐']), desc: '麻や亜麻や綿を紡いだ並の糸。' });
X('dye', '草木の染料', 'dye', 0.3, 1.5, { d: 2, make: M({ onion_skin: 3, walnut_husk: 1 }, 'weaver', 4), use: u(['dye:布・紙・革を染める', 'craft:絵の具・色インク']), desc: '身近な草木を煮出した並の染料。茶・黄・灰色が出る。' });
X('purple_dye', '紫の染料', 'dye', 0.2, 12, { r: 1, d: 1, make: M({ gromwell_root: 5, lye: 1 }, 'weaver', 12), use: u(['dye:高貴な紫（王族の衣）', 'luxury']), desc: '紫根から何度も揉み出した染料。王族にしか許されない色。' });
X('black_dye', '黒の染料', 'dye', 0.3, 3, { d: 1, make: M({ oak_gall: 3 }, 'weaver', 6), use: u(['dye:喪服・僧衣・黒い布', 'craft:黒インク']), desc: '五倍子と鉄の錆で作る黒い染料。' });
X('spice', '香辛料の合わせ', 'spice', 0.05, 4, { d: 2, make: M({ peppercorn: 1, cinnamon_bark: 1 }, 'cook', 1), keep: 700, use: u(['food:料理と菓子の香り', 'craft:香水・薬酒', 'trade']), desc: '胡椒や肉桂を挽き合わせた粉。' });
X('bean', '雑豆', 'bean', 1, 1.2, { d: 3, src: [S('harvest', ['farm', 'field'], 1)], food: 8, keep: 365, use: u(['food:煮豆・豆の粥・豆の汁', 'fertilize:畑が肥える']).concat([PLANT]), desc: 'いろいろな豆が混ざった袋。庶民の毎日の食べ物。' });
X('mushroom', '雑茸', 'mushroom', 0.1, 0.5, { d: 2, src: [S('gather', ['forest', 'dense'], 0.5)], food: 3, keep: 5, use: u(['food:汁・炒め物・煮込み']), desc: '森で集めた食べられる茸の盛り合わせ。' });
X('seaweed', '海藻', 'seaweed', 0.2, 0.3, { d: 2, src: [S('gather', ['beach'], 0.8)], food: 3, keep: 10, use: u(['food:汁・和え物', 'fertilize:浜の畑の肥やし']), desc: '浜に打ち上がった食べられる海藻の混ぜ物。' });
X('flowers', '野の花', 'flower', 0.05, 0.1, { d: 1, lim: 'none', src: [S('gather', ['grass', 'field', 'hill', 'forest'], 1)], keep: 3, use: u(['gift:花束', 'hobby:花冠', 'ritual:墓や祠の供え花']), desc: '野原で摘めるとりどりの花。' });
X('rareherb', '稀少な薬草', 'herb', 0.05, 15, { r: 2, d: 1, src: [S('forage', ['dense', 'mountain', 'swamp'], 0.05)], fx: { hp: 25 }, keep: 30, use: u(['medicine:上等な霊薬の材料', 'magic:錬金術', 'trade']), desc: '深い森や高山でまれに見つかる、名も定かでない強い薬草。' });
X('vine', '蔓', 'fiber', 0.5, 0.05, { d: 1, src: [S('gather', ['forest', 'dense', 'jungle'], 0.8)], use: u(['craft:縛る・かご・弓の弦の代わり・吊り具']), desc: '森で切ったいろいろな木の蔓。' });
X('thorn', '棘', 'branch', 0.01, 0.05, { src: [S('gather', ['desert', 'savanna', 'grass'], 0.5)], use: u(['craft:吹き矢の矢・縫い針の代わり・罠']), desc: '棘の木から折り取った鋭い棘。' });
X('orange', '甘橙', 'fruit', 0.2, 0.6, { d: 2, src: [S('harvest', ['farm'], 1), S('trade')], food: 3, keep: 30, use: u(['food:生で・汁・ジャム・砂糖漬け', 'luxury']), desc: '南の丘の甘い柑橘。' });
X('orange_sapling', '甘橙の苗木', 'sapling', 2, 4, { src: [S('trade')], make: M({ orange: 5 }, 'gardener', 24), use: u(['craft:暖かい果樹園に植える（植えれば実る）']), desc: '甘橙の若木。' });
X('citron', '枸櫞', 'fruit', 0.3, 1, { r: 1, d: 1, src: [S('harvest', ['farm'], 1), S('trade')], keep: 45, use: u(['food:皮の砂糖漬け・香りの水', 'ritual:秋の祭りの供え物']), desc: '皮の厚い大きな香る柑橘。' });
X('caper_bud', '風蝶木の蕾', 'spice', 0.01, 0.5, { src: [S('gather', ['rock', 'hill', 'beach'], 0.4)], keep: 3, use: u(['food:酢漬けにして魚料理の薬味']), desc: '岩の割れ目に生える低木の蕾。' });
X('elderflower', '接骨木の花', 'flower', 0.02, 0.2, { src: [S('gather', ['forest', 'grass'], 0.5)], keep: 2, fx: { hp: 3 }, use: u(['drink:花の甘い水・花の酒', 'medicine:風邪の汗出し', 'food:衣をつけて揚げる']), desc: '初夏の白いレースのような花。' });
X('elderwood', '接骨木の材', 'wood', 1, 3, { d: 1, src: [S('chop', ['forest', 'grass'], 0.3)], use: u(['craft:芯を抜いて笛・吹き矢の筒・エルフの弓', 'magic:杖（死者を呼ぶ木とも言う）']), desc: '芯の柔らかい接骨木の枝。' });
X('mistletoe', '宿り木', 'magicherb', 0.1, 4, { r: 1, d: 1, src: [S('gather', ['forest', 'dense'], 0.1)], use: u(['ritual:ドルイドの聖なる枝・冬至の飾り', 'magic:杖の飾り', 'medicine:血の巡り（実は毒）']), desc: '樫の高い枝に宿る常緑の株。金の鎌で刈るものとされる。' });
X('tea_silver_tip', '白毫銀針', 'drinkleaf', 0.05, 25, { r: 2, d: 1, make: M({ tea_leaf: 30 }, 'farmer', 24), keep: 700, use: u(['drink:王の茶', 'luxury', 'gift']), desc: '春一番の産毛の芽だけを摘んだ銀色の茶葉。' });
X('birch_leaf', '樺の葉', 'leaf', 0.02, 0.05, { src: [S('gather', ['forest', 'snow'], 0.6)], use: u(['drink:葉のお茶（尿の出をよく）', 'dye:黄緑']), desc: '樺の若い葉。' });
X('spruce_tip', '唐檜の新芽', 'leaf', 0.02, 0.1, { src: [S('gather', ['snow', 'mountain'], 0.5)], keep: 5, use: u(['drink:新芽の茶・唐檜の麦酒', 'medicine:冬の青物の代わり']), desc: '春の柔らかな明るい緑の芽。' });
X('pine_bark', '松の内皮', 'bark', 0.5, 0.05, { src: [S('chop', ['forest', 'mountain', 'snow'], 0.5)], use: u(['food:飢饉のとき粉にしてパンに混ぜる', 'craft:なめし']), desc: '松の皮の内側の白い層。北の民の飢えの糧。' });
X('banana_leaf', '芭蕉の葉', 'leaf', 0.3, 0.02, { src: [S('gather', ['jungle'], 0.8)], use: u(['food:肉や米を包んで蒸し焼き', 'tool:皿・雨よけ']), desc: '大きく破れやすい葉。南の国の皿。' });
X('breadfruit', '麺麭の実', 'fruit', 1.5, 0.6, { src: [S('gather', ['jungle', 'beach'], 0.5)], food: 15, keep: 3, use: u(['food:焼くとパンのよう']), desc: '南の島の大きな実。焼くとパンの味がする。' });
X('paradise_grain', '楽園の粒', 'spice', 0.02, 6, { r: 2, d: 1, src: [S('trade')], keep: 700, use: u(['food:胡椒の代わりの辛い香り', 'craft:香り酒', 'trade']), desc: '南の海岸から運ばれる辛い粒。胡椒が高すぎるときに使う。' });
X('mastic_resin', '洋乳香', 'resin', 0.05, 8, { r: 2, d: 1, src: [S('gather', ['hill', 'beach'], 0.1), S('trade')], use: u(['luxury:噛む香り樹脂', 'craft:絵のニス', 'medicine:口の病']), desc: '南の島の低木の涙のような樹脂。噛むと松の香り。' });
X('awake_leaf_raw', '目覚め葉', 'leaf', 0.02, 1.5, { r: 1, d: 1, src: [S('gather', ['mountain', 'jungle'], 0.3)], keep: 7, fx: { stamina: 15 }, use: u(['luxury:噛むと疲れと眠気が消える', 'medicine:高山の病']), desc: '山の民が噛む葉。' });
X('smokeleaf', '野の煙草葉', 'leaf', 0.1, 0.5, { src: [S('gather', ['grass', 'hill'], 0.4)], keep: 7, use: u(['craft:干して刻めばふかせる', 'ritual:祈りの煙']), desc: '野に自生する煙草の仲間の葉。畑の煙草より荒い味。' });
X('bay_leaf', '干した月桂の葉', 'spice', 0.01, 0.4, { d: 2, make: M({ laurel: 3 }, 'cook', 48), keep: 700, use: u(['food:煮込みの香り（台所用）']), desc: '台所用に干した月桂樹の葉。' });
X('willow', '柳の編み枝', 'fiber', 1, 0.4, { d: 2, make: M({ willow_twig: 2 }, 'farmer', 24), use: u(['craft:かご・行李・魚籠・盾・雪靴（皮を剥いで煮た編み材）']), desc: '柳の枝の皮を剥いで乾かした、編むための材。かご編み職人が買う。' });
X('sage', '鼠尾草の束', 'herb', 0.05, 0.5, { d: 1, make: M({ sage_herb: 3 }, 'cook', 24), keep: 365, use: u(['drink:鼠尾草茶', 'food:腸詰めの香り']), desc: '台所とお茶用に干して束ねた鼠尾草。' });
X('resin', '樹脂', 'resin', 0.3, 0.6, { d: 2, src: [S('gather', ['forest', 'dense', 'jungle', 'mountain'], 0.4)], make: M({ pine_resin: 1 }, 'carpenter', 1), use: u(['craft:接着・目止め・弓の弦と楽器の弓の滑り止め・ニス', 'fuel:松明']), desc: 'いろいろな木から集めた脂の並品。' });
X('cave_mushroom', '洞窟茸', 'mushroom', 0.1, 0.6, { d: 1, src: [S('gather', ['cave', 'mine'], 0.4)], food: 3, keep: 5, use: u(['food:煮込み・汁（光らない食べられる茸）']), desc: '洞窟の湿った暗がりに群れる白い茸。坑夫の食べ物。' });
